### ISSUE TITLE
Can't set toolbox category colour

### ISSUE THREAD

**Issue by felixerdy** [carlosperate/ardublockly#180]
I want to change the toolbox category color like described here: https://developers.google.com/blockly/guides/configure/web/toolbox#categories

What I did so far:
```js
Ardublockly.TOOLBOX_XML =
'<xml id="toolbox" style="display: none">' +
 '<category name="Control" colour="210">' +
  '<block type="controls_if"></block>' +
  '<block type="controls_whileUntil"></block>' +
  '<block type="controls_for">' +
'</category>' +
'</xml>'
```

What it displays: 
<img width="909" alt="bildschirmfoto 2017-07-14 um 11 08 42" src="https://user-images.githubusercontent.com/12086004/28206055-dd09500c-6884-11e7-92b6-08c6bca5fefc.png">

There should be a colored block next to the category name.

Thanks in advance

**Comment by felixerdy** [comment]
I was able to resolve the issue by myself:

You need to modify `.blocklyTreeRow` in `ardublockly.css` to:
```css
.blocklyTreeRow {
  background: none !important;
  /*border: none !important;*/ 
  margin: 0px 0px !important;
  padding: 7px 16px 7px 0px !important;
  box-sizing: content-box !important;
}
```
